const { autoUpdater } = require("electron-updater");
const fs = require("fs");
const path = require("path");

function readBooleanEnv(name, fallback = false) {
  const value = String(process.env[name] || "").trim().toLowerCase();
  if (!value) {
    return fallback;
  }

  if (value === "1" || value === "true" || value === "yes" || value === "on") {
    return true;
  }

  if (value === "0" || value === "false" || value === "no" || value === "off") {
    return false;
  }

  return fallback;
}

function hasBundledUpdaterConfig() {
  try {
    const configPath = autoUpdater && autoUpdater.appUpdateConfigPath ? autoUpdater.appUpdateConfigPath : "";
    if (configPath && fs.existsSync(configPath)) {
      return true;
    }
  } catch (_error) {}

  try {
    const resources = String(process.resourcesPath || "").trim();
    if (!resources) {
      return false;
    }
    const legacyPath = path.join(resources, "app-update.yml");
    return fs.existsSync(legacyPath);
  } catch (_error) {
    return false;
  }
}

function getGithubFeedConfig() {
  const owner = String(process.env.IFDA_UPDATE_OWNER || "").trim();
  const repo = String(process.env.IFDA_UPDATE_REPO || "").trim();
  const token = String(process.env.GH_TOKEN || process.env.GITHUB_TOKEN || "").trim();

  // Optional override: when owner/repo are provided we force the GitHub feed URL.
  // Otherwise electron-updater can read app-update.yml generated by electron-builder.
  if (!owner || !repo) {
    return null;
  }

  return {
    provider: "github",
    owner,
    repo,
    private: Boolean(token),
    token: token || undefined
  };
}

function createUpdateService(options = {}) {
  const app = options.app;
  let initialized = false;
  let configured = false;
  let eventsRegistered = false;
  let lastUpdateInfo = null;
  let isUpdateDownloaded = false;

  function log(message, payload) {
    if (typeof payload === "undefined") {
      console.info(`[updater] ${message}`);
      return;
    }

    console.info(`[updater] ${message}`, payload);
  }

  function emitToRenderer(channel, payload) {
    const windows = [];
    if (typeof options.getMainWindow === "function") {
      windows.push(options.getMainWindow());
    }
    if (typeof options.getFloatingWindow === "function") {
      windows.push(options.getFloatingWindow());
    }

    windows.forEach((win) => {
      try {
        if (win && !win.isDestroyed() && win.webContents && !win.webContents.isDestroyed()) {
          win.webContents.send(channel, payload);
        }
      } catch (_error) {}
    });
  }

  function resolveDisabledReason() {
    if (!app || !app.isPackaged) {
      return "development_mode";
    }

    // Default: enabled in packaged builds. Allow explicit opt-out via env.
    if (!readBooleanEnv("IFDA_AUTO_UPDATE_ENABLED", true)) {
      return "updater_disabled";
    }

    if (!getGithubFeedConfig() && !hasBundledUpdaterConfig()) {
      return "updater_not_configured";
    }

    return "";
  }

  function configureUpdater() {
    if (configured) {
      return true;
    }

    const feedConfig = getGithubFeedConfig();
    const hasBundledConfig = hasBundledUpdaterConfig();

    if (!feedConfig && !hasBundledConfig) {
      return false;
    }

    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    if (feedConfig) {
      autoUpdater.setFeedURL(feedConfig);
    }
    configured = true;
    return true;
  }

  function registerEvents() {
    if (eventsRegistered) {
      return;
    }

    eventsRegistered = true;

    autoUpdater.on("checking-for-update", () => {
      log("checking for update");
      emitToRenderer("update-status", { state: "checking" });
    });

    autoUpdater.on("update-available", (info) => {
      const version = info && info.version ? String(info.version) : "unknown";
      lastUpdateInfo = info || null;
      isUpdateDownloaded = false;
      log(`update available: ${version}`);
      emitToRenderer("update-available", {
        version,
        info: info || null
      });
      emitToRenderer("update-status", {
        state: "downloading",
        message: "Update found. Downloading...",
        version
      });
    });

    autoUpdater.on("update-not-available", () => {
      log("no update available");
      emitToRenderer("update-status", { state: "up-to-date" });
    });

    autoUpdater.on("error", (error) => {
      log("error", error && error.message ? error.message : error);
      emitToRenderer("update-status", {
        state: "error",
        message: error && error.message ? error.message : String(error || "Unknown error")
      });
    });

    autoUpdater.on("download-progress", (progress) => {
      const percent = Number(progress && progress.percent ? progress.percent : 0).toFixed(1);
      emitToRenderer("update-progress", Number(percent));
    });

    autoUpdater.on("update-downloaded", (info) => {
      const version = info && info.version ? String(info.version) : "new";
      lastUpdateInfo = info || null;
      isUpdateDownloaded = true;
      log(`update downloaded: ${version}`);
      emitToRenderer("update-status", {
        state: "ready",
        message: "Update ready. Install when you choose.",
        version
      });
      emitToRenderer("update-ready", { version });
      emitToRenderer("update-ready-silent", { version });
    });
  }

  function isUpdaterEnabled() {
    return !resolveDisabledReason();
  }

  async function checkForUpdatesManual() {
    const disabledReason = resolveDisabledReason();
    if (disabledReason) {
      return {
        ok: false,
        updateAvailable: false,
        reason: disabledReason
      };
    }

    if (!configureUpdater()) {
      return {
        ok: false,
        updateAvailable: false,
        reason: "updater_not_configured"
      };
    }

    registerEvents();

    try {
      isUpdateDownloaded = false;
      const result = await autoUpdater.checkForUpdates();
      const info = result && result.updateInfo ? result.updateInfo : null;
      if (info) {
        lastUpdateInfo = info;
      }

      const currentVersion = app && typeof app.getVersion === "function" ? app.getVersion() : "";
      const nextVersion = info && info.version ? String(info.version) : "";
      const updateAvailable = Boolean(nextVersion && currentVersion && nextVersion !== currentVersion);

      if (updateAvailable && autoUpdater.autoDownload === false) {
        void autoUpdater.downloadUpdate().catch((error) => {
          log("download failed", error && error.message ? error.message : error);
          emitToRenderer("update-status", {
            state: "error",
            message: error && error.message ? error.message : "Update download failed."
          });
        });
      }

      return {
        ok: true,
        updateAvailable,
        updateInfo: info || lastUpdateInfo,
        currentVersion,
        downloadStarted: updateAvailable
      };
    } catch (error) {
      return {
        ok: false,
        updateAvailable: false,
        reason: "check_failed",
        message: error && error.message ? error.message : String(error || "Unknown error")
      };
    }
  }

  function installUpdateNow() {
    if (!isUpdateDownloaded) {
      return {
        ok: false,
        reason: "update_not_downloaded"
      };
    }

    autoUpdater.quitAndInstall();
    return {
      ok: true,
      installing: true
    };
  }

  function initAutoUpdate() {
    if (initialized) {
      return;
    }
    initialized = true;

    const disabledReason = resolveDisabledReason();
    if (disabledReason) {
      log(`auto-update disabled (${disabledReason})`);
      return;
    }

    if (!configureUpdater()) {
      log("auto-update disabled (missing feed configuration)");
      return;
    }

    registerEvents();
    log("auto-update configured");

    // Fire-and-forget background check shortly after startup.
    const delayMs = Number.isFinite(Number(process.env.IFDA_UPDATE_CHECK_DELAY_MS))
      ? Number(process.env.IFDA_UPDATE_CHECK_DELAY_MS)
      : 5000;

    setTimeout(() => {
      autoUpdater.checkForUpdates().catch((error) => {
        log("background check failed", error && error.message ? error.message : error);
        emitToRenderer("update-status", {
          state: "error",
          message: error && error.message ? error.message : "Update check failed."
        });
      });
    }, Math.max(0, delayMs));
  }

  function initialize() {
    initAutoUpdate();
  }

  function dispose() {}

  return {
    checkForUpdatesManual,
    initAutoUpdate,
    initialize,
    installUpdateNow,
    isUpdaterEnabled,
    dispose
  };
}

module.exports = {
  createUpdateService
};
